config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  devise_for :users
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner
  has_rich_text :body


  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 25}

  self.per_page = 10
  extend FriendlyId
  friendly_id :title, use: :slugged

  def optimized_image(image,x,y)
    return image.variant(resize_to_fill: [x,y]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    return email.split("@")[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin!

  private
  def is_admin!
    if current_user && current_user.admin
    else
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
  <div class="container">
    <h1>My Blog <strong>is</strong> the <strong>true solution</strong>!</h1>
    <p>Inspire life and people around you with My Blog.</p>
    <a class="btn btn-danger" <%= link_to "Suscribe", new_user_registration_path %> </a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <span class="text-muted">@Ocean Waves 81</span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">My Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
     <% if current_user %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <%= current_user.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user.admin %>
          <a class="dropdown-item" href="<%= new_post_path %>">New Post</a>
          <% end %>
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account setting</a>
          <div class="dropdown-divider"></div>
          <%= link_to "logout", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
     <% else %>
      <li class="nav-item">
        <%= link_to "Signup", new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Signin", new_user_session_path, class: 'nav-link' %>
      </li>
     <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogVersion1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/banner' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">About me</h1>
    <div class="row">
      <p style="text-align: justify;">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id dolor porttitor, scelerisque nisl ut, tristique lacus. Morbi sed nisi finibus, tristique urna at, laoreet lorem. Aliquam scelerisque, urna eget ultricies porttitor, orci dui eleifend neque, vel placerat lectus nibh quis diam. Morbi finibus felis ipsum, eget tempus mi faucibus a. Donec at odio id nulla tempus interdum. Aenean sed felis eu tortor mattis posuere ac ut augue. Aliquam sit amet neque ut odio vestibulum porta convallis a elit. Etiam et posuere erat.
        <br>
        <br>
        Mauris suscipit enim vitae odio malesuada, vitae convallis massa ornare. Pellentesque sit amet convallis lectus. Nunc ipsum lacus, ultricies ut volutpat vitae, ultrices id sem. Nulla non arcu ac felis sollicitudin condimentum id a lectus. Pellentesque imperdiet finibus accumsan. Sed nec tempus tellus, non rutrum justo. Ut ac neque sit amet sem consectetur commodo a in nunc. Maecenas blandit, lacus non sodales posuere, est eros sodales nibh, vel convallis ex urna at elit. Etiam mi neque, mattis ac augue vel, semper vulputate leo. Phasellus sed tempus nibh, scelerisque ultrices magna. Vestibulum pellentesque eget lorem in egestas.
      </p>
      <hr class="my-4"/>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" onclick="window.location.href = 'https://facebook.com';" class="btn btn-secondary">Facebook</button>
      <button type="button" onclick="window.location.href = 'https://twitter.com';" class="btn btn-secondary">Twitter</button>
      <button type="button" onclick="window.location.href = 'https://instagram.com';" class="btn btn-secondary">Instagram</button>
      <button type="button" onclick="window.location.href = 'https://youtube.com';" class="btn btn-secondary">Youtube</button>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="container">
  <%= simple_form_for(@post) do |f| %>

    <div class="form-inputs">
      <%= f.text_field :title, class:'form-control string' %>
      <%= f.label :thumbnail, class:'form-control' %>
      <%= f.file_field :thumbnail %>
      <%= f.label :banner, class:'form-control' %>
      <%= f.file_field :banner %>
      <%= f.rich_text_area :body %>
    </div>

    <div class="btn btn-primary form-actions">
      <%= f.button :submit %>
      <%= link_to 'Back', posts_path %>
    </div>
  <% end %>

</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>My journal</h2>

<div class="container">

  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate @posts, :container => false %>
    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="row">
      <div class="card mb-3">
        <img class="card-img-top" src="<%= url_for post.optimized_image(post.thumbnail, 586,180) %>" alt="Blog post image card">
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to post.title, post %>
          </h5>
          <p class="card-text">
            <%= post.body.to_plain_text.truncate_words(50) %>
          </p>
          <p class="card-text">
            <small class="text-muted">
              <%= post.updated_at.strftime("%A, %B %e, %Y") %> by <%= post.user.username %> | <%= pluralize(post.views, "View") %> | 0 comment
            </small>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>

</div>

app/views/posts/show.html.erb
<div style="width: 100%; height: 300px; overflow-y: hidden">
  <%= image_tag(@post.thumbnail, style:'width: 100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="jumbotron" style="width: 100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4" />
      <div class="post_body">
        <%= @post.body %>
      </div>
      <% if current_user %>
          <% if current_user.admin %>
            <%= link_to "Edit", edit_post_path, class: "edit" %>
            <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?"}, class: "delete" %>
          <% end %>
      <% end %>
        <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>